--Create Database
CREATE DATABASE FINANCE_ANALYTICS;
USE DATABASE FINANCE_ANALYTICS;

--create schema
CREATE SCHEMA COMPLAINTS;
USE SCHEMA COMPLAINTS;

--Create Warehouse (Compute)
CREATE WAREHOUSE COMPLAINTS_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;
