
-- Use Database and Schema
USE DATABASE FINANCE_ANALYTICS;
USE SCHEMA COMPLAINTS;

-- Create File Format
CREATE FILE FORMAT IF NOT EXISTS complaints_csv_format
TYPE = 'CSV'
COMPRESSION = 'AUTO'
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY='"'
RECORD_DELIMITER = '\n'
SKIP_HEADER = 1
SKIP_BLANK_LINES = TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;
